gobcore/events/import_message.py
gobcore/typesystem/__init__.py
gobcore/typesystem/gob_types.py

The last fix did unfortunately not solve the complete import-to-upload problem.
This PR proposes to update the naming of the import message to be consistent with the naming of the attributes that are used internally in the import message.
The GOB.GEO has been renamed to GOB.Geo to be consistent with the naming in the import client
Default a GOB Type is not composite

Fixed types

---

gobcore/message_broker/async_message_broker.py
gobcore/typesystem/json.py
tests/gobcore/typesystem/test_json.py

Once values become instances of GOB Types, the json encoder needs to
know how to serialize them. A GOBTypeJSONEncoder is added to address
that, it needs to be called when calling json.dumps

Add JSON Encoder for GOB Types

---

setup.py
tests/gobcore/typesystem/test_gob_types.py

THe elimenates the need to add it as a requirement in other libraries. Also a test was added to compare to Strings created with None.

Added Shapely requirements in setup.py

---

gobcore/model/gobmodel.json
gobcore/typesystem/gob_types.py

Development in GOB-Import-Client diverted from the current status of the gob model definition in GOB-Core. To make them in sync again the changes have been backported.
This is pending the separation of mapping and model.

Backport from import

---

gobcore/model/gobmodel.json

When backporting changes in model in GOB-Import-Client everything was
copied, but only the non-`source_mapping` changes are needed. This
removes these

Remove backported mapping from model

---

gobcore/model/__init__.py
gobcore/model/gobmodel.json

GOBModel for meetbout was changed to match the current specification. The function get_model_fields was added to be used for database creation. It adds the _text and _id fields for references in the model.

Change GOBModel to reflect documentation

---

gobcore/events/import_events.py
gobcore/typesystem/__init__.py

Attributes was being used when applying an entity to the database ibnstead of fields. Get modification was changes to skip missing records in the database.

Fix fields and compare

---

gobcore/message_broker/messagedriven_service.py
tests/gobcore/fixtures.py
tests/gobcore/message_broker/test_message_service.py

Messagedriven service was using the same exchange for all requests. Report functionality is now optional and code has been simplified.

Improve service definition for messagedriven_service

---

gobcore/events/import_message.py
gobcore/log.py
tests/gobcore/events/test_message.py
tests/gobcore/fixtures.py

Messages on the broker are now required to have an process_id to be able to monitor the process during the steps taken in GOB. This process_id is also added to the logging.

Add process_id to logging and messages

---

gobcore/log.py

This fixes the missing data field in a log record. This can be used for extra json data used in logging

Add JSON data field to logging

---

gobcore/model/metadata.py
gobcore/typesystem/__init__.py
gobcore/views/__init__.py
gobcore/views/gobviews.json
test.sh
tests/gobcore/typesystem/test_sql_types.py
tests/gobcore/views/test_gobviews.py

Added views to gobcore to be used in the API.
Added a mapping to match SQLTypes to GOBTypes. For now a specific postgres mapping has been made and an issue has been raised to find a better solution. Tests were added. Private meta fields were added to be able to remove those from views in the API.

Add entity views

---

gobcore/model/__init__.py
gobcore/model/gobmodel.json
gobcore/typesystem/__init__.py
gobcore/views/gobviews.json

Views and model were updated to match the latest specifications needed for export. Reference id field now use the gobtype of the parent. This was needed to accept JSON reference fields. Two extra sql types were added to match to gobtypes.

Updated views and model

---

gobcore/log.py
gobcore/log_publisher.py
gobcore/message_broker/message_broker.py
test.sh
tests/gobcore/message_broker/test_sync_message_broker.py
tests/test_log_publisher.py

Logging used to establish and close a connection with the
message broker on every log message.
Now, a connection is set up once.
This connection is used for all log messages
At exit the connection is closed

Persistent log connection

---

gobcore/log.py
gobcore/log_publisher.py
tests/test_log_publisher.py

A connection is setup with the message broker when a message
is logged. The connection is left open for a few seconds to
wait for any more messages to log.
When the connection is left idle it is automatically closed.
On any new log message it is automatically reopened.

Log messages with auto disconnect from the message broker

---

gobcore/message_broker/async_message_broker.py
tests/gobcore/message_broker/test_message_broker.py

Handle messages in a separate thread.
This eliminates unexpected connection close because the application does not respond to heartbeats during the handling of a message.

Async handle msg

---

gobcore/model/gobmodel.json
gobcore/typesystem/__init__.py
gobcore/typesystem/gob_types.py
gobcore/views/gobviews.json

All models now have identificatie as entity id column to match the latest update in specs. A small fix was added to use isoformat for datetime in gob type

Renamed identificatie in model

---

gobcore/sources/__init__.py
gobcore/sources/gobsources.json
gobcore/typesystem/gob_types.py
tests/gobcore/sources/test_sources.py

GOBSources was added to be able to build relations between entities based on the value of the source they were imported from.

Add GOBSources for relations between entities

---

gobcore/message_broker/messagedriven_service.py
gobcore/model/__init__.py
gobcore/model/gobmodel.json
gobcore/model/metadata.py
gobcore/typesystem/__init__.py
gobcore/typesystem/gob_geotypes.py
gobcore/typesystem/gob_types.py
tests/gobcore/message_broker/test_message_service.py

State columns denote columns that are added to each entity that
has states. Gebieden have states where each state has a
start date, end date and a sequence number and registration date.
The sequence number and registration date are required for every
entity that has states and are added automatically.
Polygon type is used for gebieden import.
Buurten is the first entity that has been imported from the
gebieden collection

 Add state columns and polygon type, include buurten

---

gobcore/sources/gobsources.json

Relations can now be made for GOB.Reference types using the method through. A chain of links can be specified which will can be used in a sql query for the update

Add through method for relations

---

gobcore/typesystem/gob_types.py
tests/gobcore/typesystem/test_gob_types.py

Comparing a gob type reference where the relation has been made resulted in a modify event instead of a confirm because the ‘id’ had been added by the relate function. ‘id’ is now excluded when comparing references.

Fix equals function for references

---

gobcore/message_broker/async_message_broker.py
gobcore/message_broker/messagedriven_service.py
gobcore/message_broker/offline_contents.py
test.sh
tests/gobcore/message_broker/test_message_broker.py

Catch all message handler exceptions
Always acknowledge message, except when explicitly declared not to do so (result == False)
Failing messages are so removed from the queue

Improve robustness of message handler

---

gobcore/message_broker/messagedriven_service.py

When the result message is None the sending of a report message,
if so defined, is skipped

Allow for skipping result message

---

gobcore/events/__init__.py
gobcore/events/import_events.py
gobcore/events/import_message.py
gobcore/message_broker/messagedriven_service.py
gobcore/model/__init__.py
gobcore/model/gobmodel.json
gobcore/model/metadata.py
gobcore/model/sa/gob.py
tests/gobcore/events/test_message.py
tests/gobcore/fixtures.py

Register the application that is responsible for the event in the event.
Allow for changes in source for an entity by registering the entity source id.
These changes allow for maintaining a functional collection that is build from different applications.

Add application to event

---

gobcore/typesystem/gob_types.py

This resulted in an error when passing datetimes across the message bus. Isoformat will nog be handled in the API itself

Remove isoformat in json for datetime

---

gobcore/typesystem/gob_geotypes.py
tests/gobcore/typesystem/test_geo_types.py

The precision of a WKT string needs to match the precision
specified in the Geo modulce

Convert WKT geometries to include precision

---

gobcore/message_broker/async_message_broker.py
tests/gobcore/message_broker/test_message_broker.py

To prevent messages getting queued after
a long running previous message

Do not prefetch messages

---

gobcore/events/__init__.py
gobcore/events/import_events.py
gobcore/model/metadata.py
test.sh
tests/gobcore/events/test_events.py
tests/gobcore/fixtures.py

A hash field was added to be able to compare new data with the current state in the database. Tests were added to reach the required code coverage

Add hash to entities

---

gobcore/events/import_events.py

Last event is not filled for ADD events using the new comparison method, this deletes the key safely

Delete last_event only when it exists

---

gobcore/typesystem/gob_types.py
tests/gobcore/typesystem/test_gob_types.py

Dates under < 1000 are outputted differently using strftime depending on the OS. See https://bugs.python.org/issue13305. A workaround was added to make sure dates are correct in the GOB typesystem

Fix GOB dates for years < 1000

---

gobcore/typesystem/__init__.py
gobcore/typesystem/gob_geotypes.py
gobcore/typesystem/gob_types.py
gobcore/typesystem/json.py
tests/gobcore/typesystem/test_gob_types.py

Converting data to gobtypes results in a memory increase, so a function was added to all types to return python values

Add to_value function on typesystem

---

gobcore/message_broker/offline_contents.py
tests/gobcore/message_broker/test_offline_contents.py

Large messages in in GOB-Upload weren’t being offloaded because sizeof only returns the size of the reference

Temporary offload all messages

---

gobcore/database/reader/objectstore.py

Different environments require different containers on the objectstore to read from

Update objectstore reader to accept env based container name

---

gobcore/model/__init__.py
gobcore/model/gobmodel.json

Hidden attributes can be used to skip references in GraphQL and the rest API to prevent circular references. Get collection(s) now returns None if a invalid collection is requested instead of a TypeError

Hidden attributes added

---

gobcore/model/gobmodel.json
gobcore/model/metadata.py

Expiration date was added for all entities to be used in when filtering in the API for ‘active’ entities.

Add expiration date

---

gobcore/status/heartbeat.py
tests/gobcore/status/test_heartbeat.py

*Problem*: Some threads should not be reported on by heartbeat, because they don't add to the answer on "Is this application still running?".
*Solution*: Exclude threads by adding a filter mechanism. For now a filter that simply excludes thread names that start with an underscore. Example of the use-case in API service:
*The second API service only has 2 threads because we were able to exclude the thread prefixed with an underscore.*
*Additional fixes*: 
* Instantiate HearbeatConnection in tests so we can don't rely on pytest's function scoping.
* Moved thread enumeration to a new threads property.

Heartbeat thread exclusion

---

gobcore/typesystem/gob_types.py

Microseconds were also added when a different input_format was specified.

Fix microseconds bug

---

gobcore/model/gobmodel.json

Not used. Accessible through tenaamstellingen -> zakelijkrecht

Remove field 'aard zakelijkrecht' from model brk aantekeningenrechten

---

gobcore/model/gobmodel.json
gobcore/model/migrations/__init__.py
gobcore/model/migrations/gobmigrations.json
gobcore/model/sa/gob.py
tests/gobcore/model/migrations/test_migrations.py
tests/gobcore/model/sa/test_gob.py

The model for kadastralesecties changed while events had already had been imported. Truncating the table and re-applying the events resulted in an error, so the event data had to be changed to fit the new model. A migration file was added which allows for multiple changes on a version. Events will loop try to find the migration if the version of the model is newer and apply the migration to the event data before applying the event to the database.

Added a change to the model, so migrations for events was added

---

gobcore/views/gobviews.json

The following BAG collection affected:
- verblijfsobjecten (actual and history)
- nummeraanduidingen (actual and history)
- panden (actual and history)

[GOB-1139] Filter out duplicate records in Export

---

gobcore/model/__init__.py
tests/gobcore/model/test_model.py

When trying to save the source id in a collection with states the code assumed seqnr is always named ‘volgnummer’. This results in a keyerror when importing data where seqnr is defined differently e.g. ‘VOLGNUMMER’. This fix uses the supplied input_spec to get the correct field with a fallback to ‘volgnummer’.

Fix issue in get_source_id when volgnummer is named differently

---

gobcore/model/sa/gob.py

Include extra hash for attribute name to prevent collissions on index names on relation tables.

Fix index name collission on relation tables

---

gobcore/views/bag/verblijfsobjecten/enhanced_uva2.sql

To exclude duplicates caused by multiple panden for one verblijfsobject.

[GOB-1132] Change enhanced uva2 view for verblijfsobjecten

---

gobcore/views/bag/verblijfsobjecten/enhanced_uva2.sql

Removed eind geldigheid object, as this is equal to the eind_geldigheid of the selected (active) object

Cast volgnummer to integer

---

gobcore/model/gobmodel.json

Level 5 encryption generates incorrect modify events
In order to compare two entities the encrypted values for identical attributes
should compare equal. This is not yet implemented. Compare is unaware of encryption.

Change encryption level from 5 to 4

---

gobcore/model/name_compressor.py
tests/gobcore/model/test_name_compressor.py
tests/gobcore/model/test_relations.py

First get migrations working in gob-upload

Temporary disable of use NameCompressor for relation tables

---

gobcore/views/wkpb/beperkingen/enhanced.sql
gobcore/views/wkpb/brondocumenten/enhanced.sql

The source Neuron contains data which is more up to date than the source of the brondocumenten (Decos). Because the original view joins to Decos, some required records are removed.
With Karin we decided to only use the wkpb_beperkingen table for the brondocumenten export.
Now that we only use this table the brondocumenten view is the same as wkpb_beperkingen_enhanced, only the selected columns differ. So I added the columns tot the beperkingen view, that way we can remove the brondocumenten view (not immediately because the export won't work anymore).

Fix wkpb enhanced views because of relations which are not required

---

gobcore/model/sa/gob.py

The indexes for the partitioned events table are created during the migration

Partitioned events table - skip index creation

---

gobcore/model/sa/gob.py

Add an index on last_event to improve the performance of the relate queries
Example query part for gebieden-wijken:
**--** Select all entities that are newer than the rows in the relation table
src_entities AS (
SELECT * FROM gebieden_wijken WHERE _last_event > (
SELECT COALESCE(MAX(_last_src_event), 0) FROM rel_gbd_wijk_gbd_ggw__ligt_in_ggwgebied
)
)
,
-- Select all entities that are newer than the rows in the relation table
dst_entities AS (
SELECT * FROM gebieden_ggwgebieden WHERE _last_event > (
SELECT COALESCE(MAX(_last_src_event), 0) FROM rel_gbd_wijk_gbd_ggw__ligt_in_ggwgebied
)
)
,
-- Select max event that has been applied on the entities
max_src_event AS (SELECT MAX(_last_event) _last_event FROM gebieden_wijken)
,
-- Select max event that has been applied on the entities …

Rel event id index

---

gobcore/model/sa/management.py

Using the correct postgres dialect gives the option to use contains on an array. This is used in gobworkflow to check the existence of catalogue and collection in the job args column

Use postgres dialect Array to be able to use sqlalchemy ORM

---

gobcore/sources/gobsources.json

Test entities are imported using ADD and MODIFY1 as application name
In order to prevent dangling relations the test_entity_ref entities should be imported from the same application

Add relations for test_entity

---

gobcore/message_broker/initialise_queues.py
gobcore/message_broker/messagedriven_service.py
gobcore/message_broker/notifications.py
gobcore/workflow/start_workflow.py
tests/gobcore/message_broker/test_messagedriven_service.py
tests/gobcore/message_broker/test_notifications.py
tests/gobcore/workflow/test_start_workflow.py

GOB jobs can add a notification to a result message. This notification will be recognized by the message driven service. A notification message is then put on the bus on a broadcast channel. Arbitrary processes might subscribe to this notification channel and all processes will receive all broadcasts.
Broadcasting events (like the application of new events) can be used to run processes in parallel and to attach processes to the basic GOB workflow. Examples are the update of cstore tables, analysis database, Iris user interface, connector with Data Services or the distribution of notifications. This all while leaving the basic GOB Workflow untouched. Error prone time scheduling can be replaced by event driven workflows with an extra advantage that these workflows run in parallel instead of …

Notifications

---

gobcore/quality/quality_update.py
tests/gobcore/quality/test_quality_update.py

A "betwijfelde waarde" can be of any type.
When the type is a Decimal for instance the JSON serialisation would fail in the upload process
By converting the value to a string the string representation is stored and any serialisation errors are prevented

QA update stores the string value of any "betwijfelde waarde"

---

Dockerfile
gobcore/quality/issue.py
gobcore/quality/quality_update.py
tests/gobcore/message_broker/test_messagedriven_service.py
tests/gobcore/quality/test_issue.py

This solves the case that when all issues have been solved the open issues should be deleted
Formerly empty issues were skipped which resulted in issues remain open.
This is because deletion is derived from the fact that nothing is imported.
In order to prevent 'overflowing' workflow with useless QA-update jobs
only the functional jobs are processed

Also update QA catalog when no issues are present

---

gobcore/model/quality.py

The type was string, which used to be the old type for volgnummer
It should be integer to comply with the other catalogs

Change type of QA volgnummer from string to int

---

gobcore/logging/logger.py
gobcore/quality/issue.py
tests/gobcore/quality/test_issue.py

Explain in more detail how Issues are initialised
Skip issues when the logger has not been given a name.
This is for instance the case with workflow process steps

Update Issue documentation, skip issues of unnamed processes

---

gobcore/message_broker/messagedriven_service.py

If message handling has failed or no msg is returned then result_msg is None
The processing of issues, notifications and reporting should not be done

Bugfix for failing or None-returning message handler

---

gobcore/quality/issue.py
gobcore/workflow/start_workflow.py
tests/gobcore/quality/test_issue.py
tests/gobcore/workflow/test_start_workflow.py

A workflow can start with an already running workflow
In order to prevent rejected jobs for automated workflows an optional retry parameter is introduced
The conflict can arise when QA updates are processed for two attributes of an identical entity
Each attribute runs a dedicated update process on the same entity
The specification of a retry can prevent any collisions

Retry workflow

---

gobcore/datastore/oracle.py

The optimal value seems to be around the default fetchcount. Increasing or decreasing did not improve perfomance.
A value > 500 seems to have a negative impact on the performance.

Reset Oracle fetchcount to 100 rows

---

gobcore/logging/logger.py
tests/gobcore/logging/test_logger.py

Data errors were no longer recognised as errors.
Errors are fatal and should stop any further processing.
For data errors this was no longer the case and this has been corrected.

Fix bug in logger

---

gobcore/quality/issue.py
tests/gobcore/quality/test_issue.py

On creation of an Issue the begin- and eindgeldigheid are interpreted.
If any of these values is in a wrong format a ValueError was thrown
The ValueError is now catched and the value is set to None
in case of any "wrong" validiy value

Issue creation failed on illegal validity

---

gobcore/model/gobmodel.json

Now the nested JSON field attributes are used (https://github.com/Amsterdam/GOB-Core/pull/479) we found that some attributes were configured as string as they should be of the type Integer.
This PR modifies these attributes for the repository BAG.

PGB-1917 Changed json datatypes for repository BAG

---

gobcore/message_broker/messagedriven_service.py
tests/gobcore/message_broker/test_messagedriven_service.py

Currently services are started in separate threads or in one thread.
This PR allows separate services to be configured to run in a separate thread om a per-service basis.
The purpose of this change is to minimize delay in the handling of notifications.
A notification is published on the bus and should be picked up without waiting for other services in the same module to have finished.
The result of the handling of a notification is normally the start of a workflow.
By minimizing the delay in handling of notifications the workflows are started as soon as possible.

Threaded services per service

---

gobcore/datastore/bag_extract.py
tests/gobcore/datastore/bag_extract_fixtures/mutations.xml
tests/gobcore/datastore/test_bag_extract.py

Extract ElementFormatter to its own class to clean up the BAGExtractDatastore class
Sorry, should have do the refactoring in a different commit.
The actual changes aren't that big: it's mainly the changes in _get_mutation_ids and _get_elements_mutations. The first method is a new method to determine the id's to import from the mutations file. The _get_elements_mutations has an extra check on this list of ID's.

BAGExtract: Get id's to track mutations for from last full import file.

---

gobcore/datastore/objectstore.py

Empty strings need to be converted to (pandas) null values. Import sees `""` as a valid value and can't parse it as a date.

Objectstore xls read empty string as `null`

---

gobcore/datastore/objectstore.py
tests/gobcore/datastore/test_objectstore.py

This prevents making a copy of the file (bytearray -> bytes)

Return a chunk iterator or full object in get_object objectstore

---

gobcore/events/import_events.py
gobcore/model/__init__.py
gobcore/model/events.py
gobcore/model/sa/gob.py
gobcore/model/sa/indexes.py
gobcore/sources/__init__.py
tests/gobcore/model/sa/test_gob.py
tests/gobcore/model/sa/test_indexes.py
tests/gobcore/model/test_model.py
tests/gobcore/sources/test_sources.py

In preparation for legacy mode.
BREAKING CHANGES:
- Replace use of gobcore.model.sa.indexes with a call to gobcore.model.indexes.get_indexes
- Replace use of gobcore.model.sa.models with a call to gobcore.model.sa.get_sqlalchemy_models
- GOBSources needs to be initialised with an existing GOBModel from now on
GOBModel cannot be initialised in a service with both legacy True and legacy False. However, True should only be used from GOB-API.
Added some new tests for code that was previously executed during the test suite, but never really tested.
Besides the check for the legacy parameter (unused in this PR, usage will follow in a new PR), there are NO functional changes in this PR.

BREAKING - Refactor - remove all initialisations of GOBModel from GOB-Core and expect GOBModel as parameter in functions.

---

gobcore/views/nap/peilmerken/enhanced.sql

Instead of changing the query to read from public Amsterdam Schema model, read from legacy schema and initialise from API.

Change nap_peilmerken enhanced view to run on legacy schema

---

gobcore/model/__init__.py
tests/gobcore/model/test_model.py

This fixes a bug in the REST API for NAP Peilmerken in ACC and PROD.
Does not change any logic, but the order of operations has changed a bit.

Initialise rel catalog only after the object catalogs are initialised, because the rel catalog depends on them

---

gobcore/logging/logger.py
gobcore/message_broker/messagedriven_service.py
gobcore/standalone.py
gobcore/status/heartbeat.py
gobcore/utils.py
tests/gobcore/fixtures.py
tests/gobcore/logging/test_logger.py
tests/gobcore/message_broker/test_messagedriven_service.py
tests/gobcore/status/test_heartbeat.py
tests/gobcore/test_standalone.py
tests/gobcore/test_utils.py

Depends on: 
- https://github.com/Amsterdam/GOB-Core/pull/670 
- https://github.com/Amsterdam/GOB-Core/pull/672
On every message:
- Wrap the Heartbeat.progress logic in a contextmanager
- Use logger.configure_context to log to this logger in this context only
- Get the logger name from the service. From either a defined "logger" key or use the queue name as fallback.

Use logger and heartbeat context manager, get logger name from service

---

gobcore/model/gobmodel.json

Used to be a relation, but was never related as the bronwaarde was just an address. Migrated to 'object' in amsterdam schema. Caused backwards compatibility issues. Changing it to a JSON solved the issues, without causing backwards compatibility issues, as we only used the 'bronwaarde' in our exports (because there was never a relation).

Migrate nabij_nummeraanduiding relations in legacy model to JSON, as it should have been

---

gobcore/typesystem/__init__.py
tests/gobcore/typesystem/test_typesystem.py

See https://github.com/Amsterdam/amsterdam-schema/blob/master/datasets/brk2/kadastralesubjecten/v1.0.0.json
```json
"woonadres": {
"auth": "BRK/RSN",
"type": "object",
"properties": {
"type": {
"type": "string",
"description": "Woonlocatietype: 0: geen, 1: binnenland, 2: buitenland "
},
```

Allow "type" property (brk2 kadastralesubjecten woonadres).

---

gobcore/message_broker/typing.py
gobcore/standalone.py
tests/gobcore/test_standalone.py

Need to add more parameters in prepare. Extra parameters such as 'mode' should be configured in the SERVICE_DEFINITIONs
⚠️ **NOTE: BREAKING CHANGE for services that accept the 'mode' parameter**
I will update Import and Upload with the new core version once this one is merged and released.

Remove hardcoded 'mode' attribute from run_as_standalone and replace with generic solution

---

gobcore/datastore/oracle.py
requirements.txt
tests/gobcore/datastore/test_oracle.py

WIth this new oracledb package, client libraries are not necessary anymore.
- https://python-oracledb.readthedocs.io/en/latest/user_guide/introduction.html#python-oracledb-thin-mode-architecture
- https://python-oracledb.readthedocs.io/en/latest/user_guide/appendix_c.html#upgrading-from-cx-oracle-8-3-to-python-oracledb

Replace cx_Oracle with oracledb package

---

requirements.txt

- Package `pytest-cov` has been replaced by `coverage`
- Relax version constraints of `flake8` and `pydantic`

Package pytest-cov has been replaced by coverage.

---

gobcore/datastore/oracle.py
tests/gobcore/datastore/test_oracle.py

We need to use the thick mode of oracle, otherwise the the connection can (silently) fail.
The new oracledb library uses thin mode by default.
Client library files should still be available in the base image.

Initialise thick mode for oracle datastore

---

gobcore/model/gobmodel.json
gobcore/model/name_compressor.py
gobcore/sources/gobsources.json
tests/gobcore/model/test_name_compressor.py

BRK2 collections:
- stukdelen
- aantekeningenrechten
- aantekeningenkadastraleobjecten
`NameCompressor`: use `OrderedDict` to make sure the compressing order is consistent.

BRK2 stukdeel, aantekeningenrechten and aantekeningenkadastraleobjecten.

---

gobcore/message_broker/offline_contents.py
gobcore/typesystem/json.py
gobcore/utils.py
requirements.txt
tests/gobcore/message_broker/test_offline_contents.py
tests/gobcore/test_utils.py
tests/gobcore/typesystem/test_json.py

- Update ContentsReader and ContentsWriter
- Use orjson package: fast python json module replacement, same functionality
- write jsonlines (https://jsonlines.org)
- use bytes reading/writing mode (orjson/ijson take care of encoding/decoding)
- Add `ticks` method to ProgressTicker: allow progress of > 1

Improve ContentsReader/Writer performance

---

gobcore/model/gobmodel.json
gobcore/model/name_compressor.py
gobcore/sources/gobsources.json

BRK2:
- kadastralegemeentes v1.0.0
- kadastralegemeentecodes v1.0.0
- kadastraleobjecten v1.1.0
- stukdelen v1.0.1
- kadastralesubjecten v1.1.0

BRK2 & kadastralegemeentes, kadastralegemeentecodes & updates.

---

gobcore/model/sa/indexes.py
tests/gobcore/model/sa/test_indexes.py

If a relation is defined in `gobmodel.json` to a collection that doesn't exist, don't try to create an index on the destination table. Only take the defined relations in `gobsources.json` in account.

Only return dst indices for relations defined in gobsources

---

gobcore/model/gobmodel.json
gobcore/sources/gobsources.json

- GOB model updates
- GOB sources updates
- removed `begin_geldigheid` from BRK2 SDL

Updates for BRK2 TNG v2.0.0 (has_states).

---

gobcore/model/amschema/model.py
gobcore/typesystem/gob_types.py
tests/gobcore/model/test_schema.py
tests/gobcore/typesystem/test_gob_types.py

Use Amsterdam schema `multipleOf` (number type) for `GOB.Decimal` precision.

Use Adam schema multipleOf (number type) for GOB.Decimal precision.

---

gobcore/datastore/sqlserver.py
tests/gobcore/datastore/test_sqlserver.py

Sqlserver odbc driver v18 defaults to encrypt=yes, but DECOS doesn't support that.

Fix sqlserver connection for driver v18

---

gobcore/events/import_events.py
gobcore/typesystem/__init__.py
gobcore/typesystem/gob_types.py
tests/gobcore/typesystem/test_gob_types.py
tests/gobcore/typesystem/test_json.py
tests/gobcore/typesystem/test_typesystem.py

Use model type info in all GOB Types.
- Honor (Amsterdam schema) model _type_info_ (field_info) kwargs in GOB Types
- Preserve GOB.Decimal precision (default)
- Use `decimal.Decimal` for:
- Preservation of significant digits
- Rounding Numbers

Use model type_info in GOB Types.

---

gobcore/model/amschema/model.py
gobcore/model/gobmodel.json
gobcore/model/schema.py
tests/gobcore/model/test_model.py
tests/gobcore/model/test_schema.py

- Use AMS Schema for entity_id and has_states
- Set Dataset.crs to GOB default (EPSG:28992)

Use AMS Schema for entity_id and has_states.

---

gobcore/datastore/oracle.py
tests/gobcore/datastore/test_oracle.py

- Only use temporary dir during initialisation of the thick client, __del__ not necessary anymore
- Use easy connect syntax for connection string
- Disconnect already implemented in SqlDatastore
- Simplified tests
- Remove (not used) sqlalchemy `get_url` logic

Use connection string instead of dsn for oracle datastore

---

gobcore/datastore/oracle.py
gobcore/datastore/postgres.py
gobcore/datastore/sql.py
gobcore/datastore/sqlserver.py
tests/gobcore/datastore/test_oracle.py
tests/gobcore/datastore/test_postgres.py
tests/gobcore/datastore/test_sql.py
tests/gobcore/datastore/test_sqlserver.py

In case of any exception this will rollback the current transaction. 
Don't depend on calling disconnect() on the datastore for this.

Use connection contextmanager to control transaction

---

pyproject.toml
setup.py

Set environment:
```bash
export LIBGDAL_VERSION=$(gdal-config --version)
```
Check package install:
```bash
pip install git+https://github.com/Amsterdam/GOB-Core.git@install_package
```
Check package files:
```bash
pip show -f gobcore
```
Check package metadata:
```bash
pip show -v gobcore
```
Build package wheel:
```bash
pip wheel --no-deps git+https://github.com/Amsterdam/GOB-Core.git@install_package
```

Fix GOB-Core installs for regular (none editable) mode.

---

gobcore/model/amschema/model.py
tests/gobcore/amschema_fixtures/dataset_publisher.json
tests/gobcore/model/amschema/test_model.py

$ref (uri-reference) should begin with "/" but "brk2" has "publishers/BENK"

{xxx} publisher $ref fix.

---

pyproject.toml

https://packaging.python.org/en/latest/specifications/declaring-project-metadata/#dynamic
We don't have a upper limit for setuptools version, which upgraded itself to v69.
This featured a deprecation which allowed 'dynamic' metadata without explicitely specifying it in pyproject.toml

Add dependencies to dynamic
