Amsterdam/GOB-Core

- .flake8
- gobcore/__init__.py
- gobcore/events/__init__.py
- gobcore/events/import_events.py
- gobcore/events/import_message.py
- gobcore/exceptions.py
- gobcore/message_broker/messagedriven_service.py
- test.sh
- tests/gobcore/events/test_events.py
- tests/gobcore/fixtures.py
- tests/gobcore/test_message_broker.py
- tests/gobcore/test_message_service.py
The code for messages and events (both creating and interpreting them)
is added to the GOB-Core
> Add messages and events to GOB-Core

- gobcore/__init__.py
- gobcore/events/import_message.py
- gobcore/log.py
- gobcore/message_broker/__init__.py
- gobcore/message_broker/config.py
- gobcore/model/__init__.py
- gobcore/typesystem/__init__.py
- gobcore/typesystem/gob_geotypes.py
- gobcore/typesystem/gob_types.py
- requirements.txt
- setup.py
- tests/gobcore/fixtures.py
- tests/gobcore/message_broker/test_message_service.py
Added type conversion to the gob typesystem
Added logging from GOB import
Created functionality for Geo Point
> Backport functionality from GOB-Import

- gobcore/log.py
- gobcore/message_broker/config.py
Dispose both exchange and queue names in message broker config
Use the log queue name in logging module to publish log messages
> Fix logging

- gobcore/events/import_message.py
Fix error in message header attributes names
> Import message fix

- .gitignore
- gobcore/exceptions.py
- gobcore/typesystem/__init__.py
- gobcore/typesystem/gob_geotypes.py
- gobcore/typesystem/gob_types.py
- requirements.txt
- setup.py
- tests/gobcore/fixtures.py
- tests/gobcore/typesystem/test_geo_types.py
- tests/gobcore/typesystem/test_gob_types.py
Type system has been extracted but was working flaky. Especially when
comparing db values to values extracted from json.
A new interface for GOB Type has been devised, and tests have been
implemented to secure behaviour.
> Consolidate GOB Type system

- gobcore/events/import_events.py
- gobcore/message_broker/async_message_broker.py
- gobcore/typesystem/__init__.py
- gobcore/typesystem/gob_geotypes.py
- gobcore/typesystem/gob_types.py
- tests/gobcore/typesystem/test_geo_types.py
- tests/gobcore/typesystem/test_gob_types.py
- define precision in Decimal and Point
- allow Point.from_value for deserialized geojson
- disallow NaN values in json message
> Fixes issues with new GOB Typesystem

- gobcore/typesystem/__init__.py
- tests/gobcore/typesystem/test_gob_types.py
DateTime was needed for metadata and table initialisation
> Fix missing class GOB.DateTime

- gobcore/events/import_events.py
- gobcore/message_broker/async_message_broker.py
- gobcore/typesystem/gob_geotypes.py
- gobcore/typesystem/gob_types.py
- gobcore/typesystem/json.py
- requirements.txt
- tests/gobcore/typesystem/test_geo_types.py
There were some issues with adding and modifying events. Comparing None to None failed and there were some issues with reading geo data from the database.
> Fix issues

- gobcore/events/import_events.py
- tests/gobcore/fixtures.py
Using gobmodel instead of metadata
> Use gob model

- gobcore/model/gobmodel.json
Metingen model was added to gobcore
> Add metingen model

- gobcore/log.py
- gobcore/model/gobmodel.json
Referentiepunten has been added to the GOBModel
> Add referentiepunten to model

- gobcore/log.py
For now add stdout logging to show import messages
> Add stdout logging

- gobcore/model/gobmodel.json
Add rollagen to the meetbouten catalogus.
Update model description. Removed "-" from text fields.
The "-" character gets introduced by coping info from the
Stelselpedia website.
> Update model for meetbouten:rollagen

- gobcore/message_broker/async_message_broker.py
- gobcore/message_broker/initialise_queues.py
- gobcore/message_broker/messagedriven_service.py
- requirements.txt
- tests/gobcore/message_broker/test_message_broker.py
- tests/gobcore/message_broker/test_message_service.py
The message routing failed from time to time for mysterious reasons.
The message routing has been improved by linking the message handler to the corresponding
service definition.
Also, the message handler actively monitors the state of the connection. If any connection error
is detected the process is stopped.
> Fix routing errors and monitor connection status

- gobcore/model/metadata.py
- gobcore/typesystem/gob_types.py
Allows for the API to publish entity metadata
Meta can be removed from Upload
Add basic support for datetime
> Move metadata to Core

- gobcore/message_broker/async_message_broker.py
- gobcore/message_broker/config.py
- gobcore/message_broker/offline_contents.py
- test.sh
- tests/gobcore/message_broker/test_offline_contents.py
Offload large messages on shared storage
> Offload contents

- gobcore/model/__init__.py
- gobcore/model/gobmodel.json
An extra attribute references was added for easy access. The model json was updated to have catalog:collection in the ref field
> Add references to model definition

- gobcore/message_broker/config.py
Imports and exports van be started by publishing messages on these
queues
> Import and Export queues

- gobcore/model/__init__.py
- gobcore/model/gobmodel.json
- gobcore/typesystem/__init__.py
- gobcore/typesystem/gob_types.py
- gobcore/views/gobviews.json
GOBType.Reference and GOBType.ManyReference were added and the gob model was updated to reflect all findings from the acceptation tests. Views were updated accordingly.
> Add references to model and typesystem

- gobcore/events/import_message.py
- gobcore/model/gobmodel.json
- tests/gobcore/events/test_message.py
- tests/gobcore/fixtures.py
API filters were added to the model and message metadata has been fixed for upload.
> Add API filters to model

- gobcore/events/import_events.py
- gobcore/events/import_message.py
- gobcore/model/__init__.py
- gobcore/model/gobmodel.json
- gobcore/model/metadata.py
- gobcore/views/gobviews.json
- tests/gobcore/fixtures.py
- tests/gobcore/model/test_metadata.py
- tests/gobcore/model/test_model.py
Catalogs were introduced in GOBModel to provide functionality to add peilmerken to GOB. Tests added  for model.
> Add peilmerken

- gobcore/events/__init__.py
- gobcore/events/import_events.py
- gobcore/model/metadata.py
- tests/gobcore/fixtures.py
Add last event of entity to event
This serves as a check for the validity of the event
The event action should be based on the entity with equal last-event property
> Last event

- gobcore/events/import_events.py
- gobcore/model/metadata.py
The ADD event needs a little more info.
The id column needs to be known
The data is consistent with other event data and includes last_event
> last_event is Integer, ADD event info enhanced

- gobcore/model/gobmodel.json
- gobcore/views/gobviews.json
With this addition we can filter the API for publiceerbaar = True
> Publiceerbaar was added for metingen

- gobcore/model/gobmodel.json
- gobcore/views/gobviews.json
Update to the model and view, to fix the issues from the acceptance tests
> Update model and view for peilmerken

- gobcore/typesystem/gob_geotypes.py
- gobcore/typesystem/gob_types.py
- tests/gobcore/typesystem/test_gob_types.py
Valid WKT string, valid character
> Type checks improved

- gobcore/sources/__init__.py
This commit fixes the problem that relations were being overwritten by the latest source in the gobsources json file.
> Fix source relations for multiple sources

- gobcore/model/gobmodel.json
- gobcore/typesystem/__init__.py
- gobcore/typesystem/gob_geotypes.py
- test.sh
- tests/gobcore/typesystem/test_geo_types.py
A general geometry type that is able to hold any geometry
Needed for bouwblokken
> Add Geometry type

- gobcore/model/metadata.py
- gobcore/model/sa/gob.py
- test.sh
- tests/gobcore/model/sa/test_gob.py
Include description with the model
Code is copied from gobupload
The code should be removed from there after approval of this PR
Issue is generated in gobupload for this
https://github.com/Amsterdam/GOB-Upload/issues/92
> Include SQLAlchemy version of GOB Model

- gobcore/message_broker/messagedriven_service.py
Failing to process a message should not stop the processing
of other messages.
The message will be removed from the queue, a log message
is generated and the message causing the error is printed
at stdout
> Ignore messages that fail to process

- gobcore/model/gobmodel.json
- gobcore/views/gobviews.json
Added CBS-code to the GOB model and updated the rollagen enhanced view to include the centroid of the corresponding bouwlaag
> Update model and view

- gobcore/model/gobmodel.json
GGW = GebiedsGericht Werken
GGP = GebiedsGericht werken Praktijkgebieden
> Add GGW and GGP to GOB

- gobcore/sources/gobsources.json
Relations to buurten, wijken and stadsdelen needed to be added for the Basisinformatie source
> Add the relations for ggw and ggp

- gobcore/model/gobmodel.json
Fixes #GOB-511 https://datapunt.atlassian.net/browse/GOB-511
Some types were not yet added to test catalogue.
Their definition is needed to run e2e tests.
> Added missing types to test catalogue

- gobcore/model/gobmodel.json
Also: Correct error in test_entity (pk_integer field removed)
> Add BAG woonplaatsen

- gobcore/views/gobviews.json
The attribute hoort_bij_meetbout was misspelled
> Small change on views

- gobcore/message_broker/messagedriven_service.py
- gobcore/message_broker/offline_contents.py
- gobcore/status/heartbeat.py
- tests/gobcore/status/test_heartbeat.py
Send heartbeats over same connection as subscriber
to keep this connection alive
Signal failure in offloading message
print a message on stdout
> Improve heartbeats

- gobcore/model/sa/management.py
Add Jobs and JobSteps to the storage
Link log message to Jobs and Jobsteps
> Job and JobSteps

- gobcore/sources/relations.md
Proposal to model relations in GOB as regular entities.
> Model GOB relations

- gobcore/events/__init__.py
- gobcore/events/import_events.py
- tests/gobcore/events/test_events.py
- tests/gobcore/events/test_import_events.py
- tests/gobcore/fixtures.py
The bulkconfirm event was added and a function to get the attributes of an add event to be able to bulk insert entities
> Add bulkconfirm event

- gobcore/events/import_events.py
Source was missing from the event dict and thus in the database as well on all entities
> Add source to event dict

- gobcore/model/gobmodel.json
heeft_brondocumenten was added to woonplaatsen, openbareruimtes, standplaatsen, ligplaatsen
> Add heeft_brondocumenten to BAG

- gobcore/typesystem/json.py
Small change to improve compatibility
> DateTime and Date JSON conversion

- gobcore/message_broker/async_message_broker.py
- tests/gobcore/message_broker/test_message_broker.py
Set prefetch count to 1 for all channels.prefetch
The parameter cannot be overridden anymore.
> Prefetch count for all channels

- .flake8
- gobcore/database/connector/__init__.py
- gobcore/database/connector/database.py
- gobcore/database/connector/file.py
- gobcore/database/connector/objectstore.py
- gobcore/database/connector/oracle.py
- gobcore/database/connector/postgresql.py
- gobcore/database/reader/__init__.py
- gobcore/database/reader/database.py
- gobcore/database/reader/file.py
- gobcore/database/reader/objectstore.py
- gobcore/database/reader/oracle.py
- gobcore/database/writer/postgresql.py
- requirements.txt
- test.sh
- tests/gobcore/database/connector/test_database.py
- tests/gobcore/database/connector/test_file.py
- tests/gobcore/database/connector/test_objectstore.py
- tests/gobcore/database/connector/test_oracle.py
- tests/gobcore/database/connector/test_postgresql.py
- tests/gobcore/database/reader/test_database.py
- tests/gobcore/database/reader/test_file.py
- tests/gobcore/database/reader/test_objectstore.py
- tests/gobcore/database/reader/test_oracle.py
- tests/gobcore/database/writer/test_postgresql.py
- tests/gobcore/fixtures/simple_csv.csv
Moving database connectivity to GOB-Core. Result of splitting import and prepare.
> Add database connector, writer, reader functionality to core

- gobcore/database/reader/__init__.py
- gobcore/database/reader/database.py
- gobcore/database/reader/file.py
- gobcore/database/reader/objectstore.py
- gobcore/database/reader/oracle.py
- gobcore/message_broker/offline_contents.py
- tests/gobcore/database/reader/test_oracle.py
- tests/gobcore/message_broker/test_offline_contents.py
- tests/gobcore/typesystem/test_json.py
To allow for a handling per record instead of per entire collection
> Database iterators and ContentsWriter

- gobcore/sources/gobsources.json
- gobcore/views/gobviews.json
Relations for ligt_in_buurt should be determined geometrically. The view for export is now being sorted by code
> Update sources and views for bouwblokken

- gobcore/message_broker/offline_contents.py
- requirements.txt
- tests/gobcore/message_broker/test_offline_contents.py
Using ijson as streaming json parser
> Read contents entity per entity

- gobcore/database/connector/file.py
Using ijson as streaming json parser
> Restore E2E tests

- gobcore/message_broker/async_message_broker.py
- gobcore/message_broker/offline_contents.py
- tests/gobcore/message_broker/test_offline_contents.py
> Streaming contents

- gobcore/logging/logger.py
- gobcore/message_broker/config.py
- gobcore/message_broker/initialise_queues.py
- gobcore/message_broker/messagedriven_service.py
A result queue is introduced
Clients publish results on the result queue, which is further handled by the workflow manager
Job and Step id are saved in the header
Warnings and errors are saved in the logger to be reported in the result message
> Allow for workflow management

- gobcore/message_broker/messagedriven_service.py
- gobcore/status/heartbeat.py
- tests/gobcore/status/test_heartbeat.py
Report status in heartbeat message
Include message header so that any log messages are attached to the job
> Catch all workflow results

- gobcore/model/sa/management.py
https://github.com/Amsterdam/GOB-Core/issues/217
before:
after:
Speed differences for 2k records is already noticeable.
> ADD: index on services.timestamp

- gobcore/model/sa/management.py
To allow for fast recognition of new logs (query on max logid)
> Descending index on logid

- gobcore/message_broker/config.py
Allow long lasting db operations
without timing out on the message broker
> Increase pika timeouts

- gobcore/model/__init__.py
- gobcore/model/gobmodel.json
- gobcore/model/metadata.py
- gobcore/model/relations.py
- gobcore/model/sa/gob.py
- gobcore/sources/gobsources.json
- gobcore/typesystem/__init__.py
- gobcore/typesystem/gob_types.py
- tests/gobcore/model/test_relations.py
- tests/gobcore/typesystem/test_gob_types.py
VeryManyReference type was added, relation table columns changed to have bronwaarde for VeryManyReferences and validity was removed
> Add verymanyreferences

- gobcore/database/connector/__init__.py
- gobcore/database/connector/wfs.py
- gobcore/database/reader/__init__.py
- gobcore/database/reader/wfs.py
- gobcore/model/gobmodel.json
- gobcore/sources/gobsources.json
Gemeentes added to gobmodel, sources and a wfs reader was added
> Add gemeentes

- gobcore/status/heartbeat.py
- gobcore/utils.py
- tests/gobcore/status/test_heartbeat.py
Status updates are sent by means of heartbeats
Extra info is logged on stdout about the status, queue, message and
machine on which the message is processed.
> Log info about machine on which a message is processed

- gobcore/logging/log_publisher.py
- gobcore/message_broker/messagedriven_service.py
- tests/gobcore/message_broker/test_message_service.py
Give threads a name so that the threads are recognizable
> Name threads

- gobcore/message_broker/async_message_broker.py
- gobcore/message_broker/messagedriven_service.py
Try to recover from db and message broker (connection) problems
by exit program on first try and removing message on second
failure
> Fail on first try, remove message on second try

- gobcore/message_broker/async_message_broker.py
- gobcore/message_broker/utils.py
- tests/gobcore/message_broker/test_utils.py
This is to make re-usable to_json, from_json, get_message_from_body.
Also add unit test for those functions.
> Refactor AsyncConnection class

- gobcore/logging/logger.py
- gobcore/message_broker/async_message_broker.py
- gobcore/message_broker/messagedriven_service.py
Do this accross the whole repo.
> Use None to denote an empty dictionary as argument

- gobcore/views/gobviews.json
> Change views to fix issues

- .flake8
- tests/gobcore/message_broker/test_async_message_broker.py
Also do some minor code cleanup.
> Improve tests for Blocking Connection publish method

- gobcore/views/gobviews.json
Registratiedatum should be a date, add ordering to history views
> Update BAG DCT views

- gobcore/model/gobmodel.json
JSON attributes are used when dumping database tables
like is done in the API
Also corrected some copy-paste errors in description values
> Include JSON attributes

- gobcore/model/migrations/__init__.py
- tests/gobcore/model/migrations/test_migrations.py
Modify events are different from add events in their json data, this commit fixes migrations to work for modify events as well.
> Fix event migration for modify events

- gobcore/workflow/start_commands.json
Optional argument added to specify the import mode.
Default is full import
> Include mode as an import argument

- gobcore/model/gobmodel.json
And rename indicatie_woningvoorraad
> Change kadastrale objecten geometry type

- gobcore/views/brk/kadastralegemeentecodes/linegeometry.sql
- gobcore/views/brk/kadastralesecties/linegeometry.sql
Enhanced views are added to export inner lines of kadastrale gemeentecodes and kadastrale secties
> GOB-1213 Add views for exports

- gobcore/views/brk/kadastralegemeentecodes/linegeometry.sql
- gobcore/views/brk/kadastralesecties/linegeometry.sql
Was missing some fields on kadastrale secties
> Update view for kadastrale secties

- gobcore/typesystem/__init__.py
- tests/gobcore/typesystem/test_typesystem.py
Combination of enhance type info and get_gob_type
> Add get_gob_type_from_info

- gobcore/secure/config.py
- gobcore/secure/user.py
- tests/gobcore/secure/test_user.py
- tests/gobcore/typesystem/test_secure_types.py
Define headers and roles
Only gob_adm has access to secure values (for now)
> Link to keycloak

- gobcore/views/bag/ligplaatsen/enhanced_uva2.sql
- gobcore/views/bag/standplaatsen/enhanced_uva2.sql
- gobcore/views/bag/verblijfsobjecten/enhanced_uva2.sql
The following views changed:
bag/ligplaatsen/enhanced_uva2.sql
bag/standplaatsen/enhanced_uva2.sql
bag/verblijfsobjecten/enhanced_uva2.sql
> Fix woonplaatscode in enhanced uva2 views

- gobcore/model/sa/gob.py
Models with state will get an unique constraint on _id and volgnummer, other models on _id. An exception had to be made for the events column as it has no column _id
> Add unique constraints to each model

- gobcore/views/bag/verblijfsobjecten/enhanced_uva2.sql
Query updated to match specs and select most recent pand instead of a random volgnummer
> Update VOT UVA2 view

- gobcore/views/wkpb/beperkingen/enhanced.sql
- gobcore/views/wkpb/beperkingen/kadastraalobject.sql
Added new view kadastraal and changed the enhanced view.
> Changes to enhanced WKPB views, required for PGB-24

- gobcore/message_broker/initialise_queues.py
- gobcore/message_broker/messagedriven_service.py
- gobcore/model/name_compressor.py
- gobcore/views/brk/kadastralesubjecten/enhanced.sql
- tests/gobcore/model/test_name_compressor.py
- tests/gobcore/model/test_relations.py
Removed obsolete debug print messages
> Use NameCompressor for relation tables

- gobcore/model/gobmodel.json
> Add onderzoek

- requirements.txt
- setup.py
Excel reader for import and GOB-Test modules
> Add xlrd to GOB-Core setup

- gobcore/logging/logger.py
- gobcore/quality/issue.py
- tests/gobcore/logging/test_logger.py
An ExtendedLogger was created to add extra loglevels to distinguish between process logging and data logging.
Data Issues log using these log levels
> Separate data logging from process logging

- gobcore/model/quality.py
- gobcore/quality/issue.py
- gobcore/quality/quality_update.py
- tests/gobcore/quality/test_issue.py
Add the attributes to the Issue.
Checked the usage of Issue(). Only IMPORT and RELATE_CHECK report issues
They have been marked as functional process steps so that also empty sets will get reported (deletions)
> PGB 1287 Add begin- and eind-geldigheid to QA Catalog

- gobcore/quality/issue.py
- tests/gobcore/quality/test_issue.py
Geldigheid datums are always datetime
GOBPrepare issues are skipped (as it is from an external database)
> PGB 1310 correct geldigheid datum en skip GOB Prepare jobs

- gobcore/model/gobmodel.json
Change the name of BAG onderzoek to onderzoeken
> Rename BAG onderzoek to onderzoeken

- gobcore/typesystem/gob_geotypes.py
- tests/gobcore/typesystem/test_geo_types.py
Modify events take a lot of time to process
Around 10% of the time is spent on GEO type initialization
The code has been profiled and optimized
The method now takes nearly no time at all and the whole compare process is 10% faster
> Optimize geo type initialisation

- gobcore/model/gobmodel.json
- gobcore/sources/gobsources.json
Add the attribute to each BAG entity in GOB model
Add a Neuron resolver for each heeft_onderzoeken attribute in GOB sources
Also corrected some copy-paste errors in description fields
> Add heeft_onderzoeken to BAG entities

- gobcore/datastore/oracle.py
- requirements.txt
- setup.py
Increased fetch count (default 100 set to 1000)
Update cx_oracle lib
> Improve Oracle reader performance

- gobcore/message_broker/notifications.py
- gobcore/quality/quality_update.py
- tests/gobcore/quality/test_issue.py
PGB-1620 Use process_id of original job in QA update jobs.
> PGB-1620 Include process_id in notifications

- gobcore/model/gobmodel.json
- gobcore/model/migrations/gobmigrations.json
- gobcore/views/bag/nummeraanduidingen/enhanced.sql
- gobcore/views/bag/nummeraanduidingen/enhanced_history.sql
- gobcore/views/bag/verblijfsobjecten/enhanced.sql
- gobcore/views/bag/verblijfsobjecten/enhanced_history.sql
Datamigration was added as well
> Remove aanduiding_in_onderzoek from VOT, NUM and OPR

- gobcore/workflow/start_commands.json
> Add mode as named parameters

- gobcore/quality/config.py
Added a QA check to check the format of brondocument - documentnummer (will be used for both wkpb and bag
> PGB-2221 Add QA check for Value_brondocument_coding

- gobcore/message_broker/config.py
- gobcore/workflow/start_commands.json
Zou niks moeten breken, nodig om workflow aan de raat te krijgen.
> Pgb 2970/add bag extract msg queue

- gobcore/quality/issue.py
- tests/gobcore/quality/test_issue.py
A lot of empty files were created in the shared message_broker folder and never deleted.
> Delete file if no issues were found

- gobcore/events/__init__.py
- gobcore/events/import_events.py
- gobcore/model/__init__.py
- gobcore/model/metadata.py
- gobcore/model/sa/gob.py
- tests/gobcore/events/test_events.py
- tests/gobcore/events/test_import_events.py
- tests/gobcore/fixtures.py
- tests/gobcore/model/sa/test_gob.py
- tests/gobcore/model/test_model.py
Use TID on events instead of source/source_id combination.
> Use TID in events instead of source/source_id

- gobcore/views/bag/panden/enhanced.sql
because of new relation between pand and gebieden buurten.
> Modified Pand enhanced view

- gobcore/datastore/oracle.py
- tests/gobcore/datastore/test_oracle.py
failover for multiple hosts in config
> 8228 multiple hosts for failover

- gobcore/datastore/oracle.py
Encryption is now required for all Oracle connections.
cx_Oracle version 7.3.0 only supports setting through the
TNS_ADMIN environment variable.
> Enforce encryption on the Orcale DB layer.

- gobcore/model/gobmodel.json
> Change brk meta to string

- gobcore/message_broker/async_message_broker.py
- gobcore/model/gobmodel.json
- gobcore/sources/gobsources.json
- gobcore/status/heartbeat.py
- gobcore/views/bag/panden/enhanced.sql
- gobcore/views/bag/panden/enhanced_history.sql
- gobcore/views/bag/verblijfsobjecten/enhanced.sql
- gobcore/views/bag/verblijfsobjecten/enhanced_history.sql
#23212
Fix typo in heartbeat.py
> Remove _ from gebieden relations

- gobcore/model/gobmodel.json
- gobcore/model/migrations/gobmigrations.json
> Add migrations for buurten and wijken

- .gitignore
- requirements.txt
Upgrades a few requirements to make them work with m1 macs.
> Upgrade requirements to make them work on m1 macs

- gobcore/enum.py
- gobcore/typesystem/json.py
- tests/gobcore/typesystem/test_json.py
Generates empty import to mark all entities as deleted
> Add import mode `delete`

- gobcore/model/gobmodel.json
- gobcore/model/migrations/gobmigrations.json
- gobcore/sources/gobsources.json
- gobcore/views/bag/verblijfsobjecten/enhanced.sql
- gobcore/views/bag/verblijfsobjecten/enhanced_history.sql
- ligplaatsen
- standplaatsen
- nummeraanduidingen
- verblijfsobjecten
> Add ligt_in_gemeente to more bag collections

- requirements.txt
mitigate https://github.com/advisories/GHSA-ffqj-6fqr-9h24
> Update PyJWT to 2.4.0

- gobcore/model/migrations/__init__.py
- gobcore/model/migrations/gobmigrations.json
- gobcore/views/nap/peilmerken/enhanced.sql
- tests/gobcore/model/migrations/test_migrations.py
Don't release to 'GOB-Upload' yet. Needs the other GOB-Core PR as well.
> Add splitjson type migration for NAP Peilmerken, edit enhanced view

- gobcore/datastore/objectstore.py
- gobcore/logging/logger.py
- gobcore/message_broker/offline_contents.py
- gobcore/quality/issue.py
- gobcore/utils.py
- gobcore/workflow/start_commands.json
- gobcore/workflow/start_commands.py
- requirements.txt
- tests/gobcore/datastore/test_objectstore.py
- tests/gobcore/logging/test_logger.py
- tests/gobcore/message_broker/test_offline_contents.py
- tests/gobcore/quality/test_issue.py
- tests/gobcore/workflow/test_start_commands.py
- Re-use WorkflowCommands from GOB-Workflow 
- Optionally add messagebroker logging handler
- Log default to stdout
- Optionally give destination path for content output
Also fixed:
- replace xlrd (not maintained) with openpyxl
- Use read() on get_object from objectstore
- add typing to logging.py
> Import standalone application

- gobcore/datastore/xcom_data_store.py
- gobcore/message_broker/offline_contents.py
- tests/gobcore/datastore/test_xcmom_data_store.py
[AB#51361](https://dev.azure.com/CloudCompetenceCenter/7755cdf4-1859-48c5-b954-fd6c8e46fe52/_workitems/edit/51361)
> Add XComDataStore

- gobcore/datastore/xcom_data_store.py
- tests/gobcore/datastore/test_xcmom_data_store.py
[AB#49818](https://dev.azure.com/CloudCompetenceCenter/7755cdf4-1859-48c5-b954-fd6c8e46fe52/_workitems/edit/49818)
> Remove XComData model from xcom data store

- gobcore/model/amschema/model.py
- gobcore/model/gobmodel.json
- gobcore/model/migrations/gobmigrations.json
- gobcore/model/pydantic.py
- gobcore/model/schema.py
- gobcore/sources/gobsources.json
- gobcore/views/bag/brondocumenten/enhanced.sql
- gobcore/views/bag/brondocumenten/enhanced_history.sql
- gobcore/views/bag/nummeraanduidingen/enhanced.sql
- gobcore/views/bag/nummeraanduidingen/enhanced_history.sql
- gobcore/views/bag/panden/enhanced.sql
- gobcore/views/bag/panden/enhanced_history.sql
- gobcore/views/bag/verblijfsobjecten/enhanced.sql
- gobcore/views/bag/verblijfsobjecten/enhanced_history.sql
- gobcore/views/brk/kadastralesubjecten/enhanced.sql
- gobcore/views/meetbouten/referentiepunten/enhanced.sql
- gobcore/views/meetbouten/rollagen/enhanced.sql
- gobcore/views/wkpb/beperkingen/kadastraalobject.sql
- requirements.txt
- tests/gobcore/model/test_schema.py
[AB#49899](https://dev.azure.com/CloudCompetenceCenter/7755cdf4-1859-48c5-b954-fd6c8e46fe52/_workitems/edit/49899)
> #49899 Source gebieden from Amsterdam Schema

- gobcore/views/bag/brondocumenten/enhanced_history.sql
- gobcore/views/bag/nummeraanduidingen/enhanced.sql
- gobcore/views/bag/nummeraanduidingen/enhanced_history.sql
- gobcore/views/bag/panden/enhanced.sql
- gobcore/views/bag/panden/enhanced_history.sql
- gobcore/views/bag/verblijfsobjecten/enhanced.sql
- gobcore/views/bag/verblijfsobjecten/enhanced_history.sql
- gobcore/views/brk/kadastralesubjecten/enhanced.sql
- gobcore/views/meetbouten/referentiepunten/enhanced.sql
- gobcore/views/meetbouten/rollagen/enhanced.sql
- gobcore/views/wkpb/beperkingen/enhanced.sql
- gobcore/views/wkpb/beperkingen/kadastraalobject.sql
- gobcore/views/wkpb/brondocumenten/enhanced.sql
Little oopsie in the sed replaces from my last PR 🙈
> Fix introduced errors in views from last PR 🙈

- Dockerfile
- docker-compose.yml
- gobcore/datastore/oracle.py
- gobcore/message_broker/config.py
- gobcore/model/README.md
- gobcore/model/__init__.py
- test.sh
- tests/gobcore/model/sa/test_indexes.py
- tests/pytest.ini
Kijk nog even naar de `/airflow` directory (`Dockerfile`).
> Migrate to GOB base and wheelhouse images; run as datapunt user.

- gobcore/message_broker/messagedriven_service.py
- gobcore/standalone.py
- boyscout: remove a debug message
> Move logger config out of try clause

- requirements.txt
https://github.com/Amsterdam/GOB-Core/security/dependabot/3
> Update oslo-utils to 4.10.2

- gobcore/message_broker/messagedriven_service.py
- gobcore/message_broker/typing.py
- gobcore/standalone.py
- gobcore/status/heartbeat.py
Depends on: https://github.com/Amsterdam/GOB-Core/pull/670 ✅
> Add service typing

- gobcore/sources/gobsources.json
Use the new AmsterdamSchema relation names for `meetbouten`
> Use new relation names for meetbouten

- docker-compose.yml
- gobcore/model/amschema/repo.py
This reverts commit 592de942dd85615d5ff8439e16a0884e4dce58a2.
Instead use REPO_BASE env var
> Revert "Temp workaround brk2"

- .flake8
- Dockerfile
- gobcore/__init__.py
- gobcore/enum.py
- pyproject.toml
- requirements-dev.txt
- requirements.txt
- test.sh
- tests/pytest.ini
- No need for seperate .flake8 config file (flake8-pyproject)
- Remove pytest.ini
- All config in pyproject.toml
- Allow per file enabling of checks
- linelength = 120
Temporary disabled `mypy` checks. Due to imports in __init__.py, a lot of files need to be checked. 
This will be a seperate pr
> Code checks

- gobcore/message_broker/offline_contents.py
- gobcore/standalone.py
- tests/gobcore/test_standalone.py
- Read offloaded contents using ContentsReader
- Remove content streamer from result message
> In standalone mode, always stream contents

- gobcore/model/gobmodel.json
- gobcore/sources/gobsources.json
BRK 2:
- stukdelen v1.0.2 (bedragTransactie, relations)
- zakelijkerechten v1.2.0 (brk2:kadastralesubjecten)
> BRK2 fixes

- gobcore/model/gobmodel.json
- gobcore/sources/gobsources.json
BRK2:
- kadastralegemeentes v1.1.0: ligtInBrkGemeente relation.
> BRK2: the last mile.

- gobcore/message_broker/typing.py
- gobcore/standalone.py
- gobcore/status/heartbeat.py
- gobcore/workflow/start_commands.py
- gobcore/workflow/typing.py
- test.sh
Code checks for:
- gobcore.standalone
- gobcore.status.heartbeat
- gobcore.workflow.start_commands
> Some code checks.

- gobcore/model/gobmodel.json
- BRK2 sync Amsterdam schema
- NAP & meetbouten decimal precision
> BRK2 sync Amsterdam schema.

- gobcore/quality/issue.py
- gobcore/quality/quality_update.py
- tests/gobcore/quality/test_issue.py
- tests/gobcore/quality/test_quality_update.py
- If importing from GOBPrepare, the qa was skipped
- Add typing
- Remove empty issues file
- simplify process_issues
> Fix trigger QA workflow

- gobcore/datastore/oracle.py
- requirements.txt
- tests/gobcore/datastore/test_oracle.py
- Fix: Only set `load_balance=off` for multiple hosts 
- Bump vulnerable cryptography: https://github.com/advisories/GHSA-5cpq-8wj7-hf2v
> Refactor build connection string

- gobcore/model/amschema/model.py
- gobcore/model/gobmodel.json
- tests/gobcore/amschema_fixtures/__init__.py
- tests/gobcore/amschema_fixtures/dataset_publisher.json
- tests/gobcore/model/amschema/test_model.py
implements https://schemas.data.amsterdam.nl/docs/ams-schema-spec.html#publisher-refs
> Add Publisher model for amschema + brk2 aardzakelijkerechten

- gobcore/message_broker/async_message_broker.py
Forces to exit thread if main thread dies
> Daemonize message handler thread

- gobcore/datastore/postgres.py
- tests/gobcore/datastore/test_postgres.py
fixes: `the connection cannot be re-entered recursively`
> Use custom contextmanager for transaction

- gobcore/model/gobmodel.json
- gobcore/sources/gobsources.json
> Changed {xxx} datasetId to hr (relations).

- gobcore/model/gobmodel.json
- gobcore/sources/gobsources.json
- tests/gobcore/model/test_model.py
depends on https://github.com/Amsterdam/amsterdam-schema/pull/796 ✅
> Add `monumenten` collection

- gobcore/model/gobmodel.json
depends on: https://github.com/Amsterdam/amsterdam-schema/pull/812
> Update monumenten version

- gobcore/datastore/postgres.py
- tests/gobcore/datastore/test_postgres.py
PostgresDatastore `table_count` function for prepare quality checks.
> Count the number of rows in a Postgres table.

- gobcore/sources/gobsources.json
Run as standalone GOB-Upload fails on the old relation names
> Update ggpgebieden sources to amschema

- gobcore/model/gobmodel.json
GOBModel: gebruik BRK2:gemeentes ipv BRK:gemeentes voor bag en gebieden
> GOBModel: gebruik BRK2:gemeentes ipv BRK:gemeentes voor bag en gebieden
